### ISSUE TITLE
Add ids of icons in html demo file

### ISSUE THREAD

**Issue by dhawkmoon** [elrumordelaluz/svgsprit.es#1] opened 2019-02-06 10:50 UTC
Hello, and thank you for great app, that saved me a lot of time. 

Still, I want to ask you to add ids for icons as text in demo html file, so user can easily copy and paste id of desired icon.

Also there is a little bug: ids in generated sprite sometimes messed up.

Here some images:

http://prntscr.com/mhcexs - wrong ids

http://prntscr.com/mhcfj2 - the idea to place icon ids under icons

Thank you

**Comment by elrumordelaluz** [comment] 2019-02-06 21:28
Hi @dhawkmoon, thanks for the _Issue_.

> ids in generated sprite sometimes messed up.

Did that happen every time you try with the same icons? In that case could you share them to chek on my end? 
Probably is related on the loop from the _files_ to obtain the _filenames_.

Regarding the `id` in the _demo_, right now renders the exact output [svg-spreact](https://github.com/elrumordelaluz/svg-spreact) produces, where is probably the best place to return also an `Array` with those _ids_.

**Comment by dhawkmoon** [comment] 2019-02-11 07:22
Hi @elrumordelaluz,

Actually I've tried two separate packs of icons, and in both cases ids were messed up.

Here I've uploaded one of them:

Here is an input:
[input.zip](https://github.com/elrumordelaluz/micro-svg-spreact/files/2850120/input.zip)

Here is an output:
[output.zip](https://github.com/elrumordelaluz/micro-svg-spreact/files/2850093/output.zip)

I hope it will help.

**Comment by elrumordelaluz** [comment] 2019-02-12 09:34
Hi @dhawkmoon,
Seems pretty weird the _demo_ generated, I am sorry for that.

Can you tell me which browser/os are you using? I can't reproduce on my end, every time I test all the /input _Icons_, the generated code is ok.

**Comment by dhawkmoon** [comment] 2019-02-14 04:16
@elrumordelaluz Currently I'am using MacOs Mojave 10.14.2 with Chrome 71.0.3578.98

**Comment by willrstern** [comment] 2019-03-08 17:18
I ran into the same thing today: sprite ids are randomized each time for me on mac/chrome.
Gotta say, though, AWESOME TOOL @elrumordelaluz!   If the id's match the filenames, it will save enormous amounts of time!

**Comment by jmwill86** [comment] 2019-04-11 15:16
Nice little tool. Id's are mixed up for me on Chrome, Firefox works fine though.

**Comment by floor12** [comment] 2019-12-07 12:09
> I ran into the same thing today: sprite ids are randomized each time for me on mac/chrome.
> Gotta say, though, AWESOME TOOL @elrumordelaluz! If the ids match the filenames, it will save enormous amounts of time!

> I ran into the same thing today: sprite ids are randomized each time for me on mac/chrome.

I have the same problem today.

**Comment by fzngagan** [comment] 2020-07-10 15:19
Thanks for the free tool. Appreciate the effort. I'm getting around by converting each file separately.

**Comment by elrumordelaluz** [comment] 2021-06-15 07:25
Should be fixed by #32

**Closed by elrumordelaluz** 2021-06-15 07:25 UTC
Labels: bug
